export const optionItems = [
  {
    id: 1,
    title: 'تشکیل شده',
    icon: process.env.PUBLIC_URL + 'images/options/created.svg',
    defaultTheme: 'light_pink',
    code: '۳۳۶',
  },
  {
    id: 2,
    title: 'ارسال شده به شرکت ارزیابی',
    icon: process.env.PUBLIC_URL + 'images/options/sent.svg',
    defaultTheme: 'light_purple',
    code: '۴۴۵',
  },
  {
    id: 3,
    title: 'آرشیو شده',
    icon: process.env.PUBLIC_URL + 'images/options/archive.svg',
    defaultTheme: 'light_green',
    code: '۶۶۵',
  },
  {
    id: 4,
    title: 'در حال اجرا',
    icon: process.env.PUBLIC_URL + 'images/options/proccessing.svg',
    defaultTheme: 'light_orange',
    code: '۲۵۵',
  },
  {
    id: 5,
    title: 'ارزیابی شده',
    icon: process.env.PUBLIC_URL + 'images/options/checked.svg',
    defaultTheme: 'light_pink',
    code: '۲۵۵',
  },
  {
    id: 6,
    title: 'برگشت به شرکت ارزیابی',
    icon: process.env.PUBLIC_URL + 'images/options/returned.svg',
    defaultTheme: 'light_purple',
    code: '۲۵۵',
  },
  {
    id: 7,
    title: 'بازدید مجدد',
    icon: process.env.PUBLIC_URL + 'images/options/revisit.svg',
    defaultTheme: 'light_green',
    code: '۲۵۵',
  },
  {
    id: 8,
    title: 'بسته شده',
    icon: process.env.PUBLIC_URL + 'images/options/closed.svg',
    defaultTheme: 'light_orange',
    code: '۲۵۵',
  },
]
