export const optionItems = [
  {
    id: 1,
    title: 'تشکیل شده',
    icon: process.env.PUBLIC_URL + 'images/options/created.svg',
    defaultTheme: 'lightPink',
    code: '336',
  },
  {
    id: 2,
    title: 'ارسال شده به شرکت ارزیابی',
    icon: process.env.PUBLIC_URL + 'images/options/sent.svg',
    defaultTheme: 'lightPurple',
    code: '445',
  },
  {
    id: 3,
    title: 'آرشیو شده',
    icon: process.env.PUBLIC_URL + 'images/options/archive.svg',
    defaultTheme: 'lightGreen',
    code: '665',
  },
  {
    id: 4,
    title: 'در حال اجرا',
    icon: process.env.PUBLIC_URL + 'images/options/proccessing.svg',
    defaultTheme: 'lightOrange',
    code: '255',
  },
  {
    id: 5,
    title: 'ارزیابی شده',
    icon: process.env.PUBLIC_URL + 'images/options/checked.svg',
    defaultTheme: 'lightPink',
    code: '255',
  },
  {
    id: 6,
    title: 'برگشت به شرکت ارزیابی',
    icon: process.env.PUBLIC_URL + 'images/options/returned.svg',
    defaultTheme: 'lightPurple',
    code: '255',
  },
  {
    id: 7,
    title: 'بازدید مجدد',
    icon: process.env.PUBLIC_URL + 'images/options/revisit.svg',
    defaultTheme: 'lightGreen',
    code: '255',
  },
  {
    id: 8,
    title: 'بسته شده',
    icon: process.env.PUBLIC_URL + 'images/options/closed.svg',
    defaultTheme: 'lightOrange',
    code: '255',
  },
]
